export const AzFuncBindingNameReturn = 'tsapiazfreturnvaldonotuseasyourreturnvalue';

export const enum AzFuncBinding {
	HttpTrigger = 'httpTrigger',
	Http = 'http',
	TimerTrigger = 'timerTrigger',
	BlobTrigger = 'blobTrigger',
	Blob = 'blob',
	Queue = 'queue',
	QueueTrigger = 'queuetrigger',
	Table = 'table',
	ServiceBusTrigger = 'servicebustrigger',
	ServiceBus = 'servicebus',
	EventHubTrigger = 'eventhubtrigger',
	EventHub = 'eventhub',
	SendGrid = 'sendgrid',
	ActivityTrigger = 'activitytrigger',
	OrchestionTrigger = 'orchestrationtrigger',
	OrchestrationClient = 'orchestrationclient',
	EventGridTrigger = 'eventgridtrigger',
	CosmosDBTrigger = 'cosmosdbtrigger',
	CosmosDB = 'cosmosdb',
	TwilioSms = 'twiliosms',
	SignalR = 'signalr',
	SignalRConnectionInfo = 'signalrconnectioninfo',
}